### ISSUE TITLE
Can I use? 

### ISSUE THREAD

**Issue by ghost** [luciotato/waitfor#38]
I think about this:

```
var anchor = locker(1000); //lock maximum 1 seconds
somethingAsync(function() {
  anchor.unlock()
});
lock.lock(); //lock (if not commanded unlock) 
```

Can I use it?

**Comment by luciotato** [comment]
I do not follow what are you trying to achieve.

**Comment by acterhd** [comment]
I not try. But I want make synchronization, but lock before callback, and
unlock after callback.
26 окт. 2015 г. 21:19 пользователь "Lucio M. Tato" <notifications@github.com>
написал:

**Comment by luciotato** [comment]
maybe:

    var anchor = locker(1000); //lock maximum 1 seconds
    anchor.lock(); //lock (if not commanded unlock)
    var result := wait.for(somethingAsync);
    anchor.unlock();

**Comment by acterhd** [comment]
I think last function can be removed.
26 окт. 2015 г. 21:26 пользователь "Lucio M. Tato" <notifications@github.com>
написал:

**Comment by acterhd** [comment]
I thinked about wait calling some async function. Or when condition
operation (async) will true.
26 окт. 2015 г. 21:30 пользователь "Alexey Solovey" <acterhd@gmail.com>
написал:
