### ISSUE TITLE
wait.for inside eval()

### ISSUE THREAD

**Issue by KaMeHb-UA** [luciotato/waitfor#44]
That code throws an error "Callback called twice" but... there is no twice-called functions. Problem in eval()? But what can I do, if i can't exclude this stage? I MUST use wait.for inside eval()'ed functions. [Error demo](https://runkit.com/embed/yz68zrdm3d1l)
```` javascript
var wait = require("wait.for")
var contents = 'write("You must wait 5 seconds before page loads...<br/>");\
var a = wait.for(function(callback1){\
    setTimeout(function(){\
        callback1(null, "Hell O MFs");\
    }, 5000);\
});\
exit(null, a);';
function route(){
    eval('function page(write,exit){' + contents + '}');
    var fakewrite = function(a){console.log(a)};
    wait.for(page,fakewrite);
}
wait.launchFiber(route);
````

**Comment by luciotato** [comment]
Sorry I can't help you. I'm not doing support for this.

**Comment by KaMeHb-UA** [comment]
It's bad..
Ok, I'll test one more way to get it works. Thanks for reply!

**Comment by markcollinscope** [comment]
Dear KaMeHb-UA.

Luciotato's wait.for module was a godsend to me. Solved so many problems. And it works great. 

So great, in fact, that Nodejs 8 seems to have copied it [await].

So I'd (with respect) suggest you look at the documentation and your own code and try to work out the issue yourself.

Kind regards,
Mark.
